server.port: 8080
spring:
  application.name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pitchouneee/spring-cloud-config-client.git
#          username: <username>
#          password: <password>